# Generated by Django 5.1.6 on 2025-02-27 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PredictionFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('schema', models.JSONField(default=list)),
                ('has_date_column', models.BooleanField(default=False)),
                ('date_columns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictionfile.UploadedFile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
