# Generated by Django 5.1.2 on 2024-11-11 11:31

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_uploadedfile_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=chat.models.upload_to),
        ),
    ]
