# Generated by Django 5.1.2 on 2024-11-19 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='chat.uploadedfile')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
