# Generated by Django 5.1.2 on 2025-01-14 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_notebookmetadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_column', models.CharField(max_length=255)),
                ('target_column', models.CharField(max_length=255)),
                ('time_column', models.CharField(blank=True, max_length=255, null=True)),
                ('time_frame', models.CharField(blank=True, max_length=255, null=True)),
                ('time_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.JSONField()),
                ('file_url', models.URLField()),
                ('notebook_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatbackup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='NotebookMetadata',
        ),
    ]
