# Generated by Django 5.1.2 on 2025-01-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_notebook_chat_notebook_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='chat_id',
            new_name='chat',
        ),
    ]
