# Generated by Django 5.1.4 on 2025-02-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_predictivesettings_machine_learning_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='cell_s3_links',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
