# Generated by Django 5.1.2 on 2025-03-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_chatfileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivesettings',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
