# Generated by Django 5.1.2 on 2025-03-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_predictivesettings_prediction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictivesettings',
            name='new_target_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
